import { User, Document } from "./types";

export const MOCK_USERS: Record<number, User> = {
  1: {
    id: 1,
    name: "TS. Nguyễn Văn A",
    email: "nguyenvana@university.edu.vn",
    role: "teacher",
    status: "ACTIVE",
  },
  2: {
    id: 2,
    name: "Phòng Đào Tạo",
    email: "daotao@university.edu.vn",
    role: "admin",
    status: "ACTIVE",
  },
};

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: 101,
    title: "Lập trình Web với React",
    description: "Giáo trình hướng dẫn xây dựng ứng dụng SPA với React và TypeScript, dành cho sinh viên năm 3.",
    subject: "Kỹ thuật phần mềm",
    topic: "Lập trình Web",
    chapter: "Chương 1-5",
    tags: ["React", "Frontend", "Web", "TypeScript"],
    authorId: 1,
    authorName: "TS. Nguyễn Văn A",
    uploadedAt: "10/03/2024",
    updatedAt: "12/03/2024",
    fileType: "PDF",
    fileSize: "2.4 MB",
    mimeType: "application/pdf",
    pageCount: 120,
    chunkCount: 350,
    processingStatus: "PROCESSED",
    publicationStatus: "PUBLISHED",
    publishedAt: "12/03/2024",
    reviewedByName: "Phòng Đào Tạo",
  },
  {
    id: 102,
    title: "Cấu trúc dữ liệu và giải thuật",
    description: "Tài liệu ôn tập môn Cấu trúc dữ liệu, tập trung vào đồ thị và cây.",
    subject: "Khoa học máy tính",
    topic: "Cấu trúc dữ liệu",
    tags: ["Algorithm", "Graph", "Tree"],
    authorId: 1,
    authorName: "TS. Nguyễn Văn A",
    uploadedAt: "15/03/2024",
    updatedAt: "15/03/2024",
    fileType: "PDF",
    fileSize: "5.1 MB",
    mimeType: "application/pdf",
    pageCount: 85,
    chunkCount: 210,
    processingStatus: "PROCESSED",
    publicationStatus: "PENDING_REVIEW",
  },
  {
    id: 103,
    title: "Nhập môn Trí tuệ nhân tạo",
    description: "Slide bài giảng giới thiệu về AI, Machine Learning cơ bản.",
    subject: "Khoa học máy tính",
    topic: "Trí tuệ nhân tạo",
    tags: ["AI", "Machine Learning"],
    authorId: 1,
    authorName: "TS. Nguyễn Văn A",
    uploadedAt: "18/03/2024",
    updatedAt: "19/03/2024",
    fileType: "PDF",
    fileSize: "3.2 MB",
    mimeType: "application/pdf",
    pageCount: 45,
    chunkCount: 90,
    processingStatus: "PROCESSED",
    publicationStatus: "REJECTED",
    rejectReason: "Thiếu phần tài liệu tham khảo ở cuối slide. Đề nghị bổ sung để sinh viên tự học.",
    reviewedAt: "19/03/2024",
    reviewedByName: "Phòng Đào Tạo",
  },
  {
    id: 104,
    title: "Mạng máy tính căn bản",
    description: "Nội dung thực hành cấu hình router và switch Cisco.",
    subject: "Mạng máy tính",
    topic: "Thực hành mạng",
    tags: ["Network", "Cisco", "Routing"],
    authorId: 1,
    authorName: "TS. Nguyễn Văn A",
    uploadedAt: "20/03/2024",
    updatedAt: "20/03/2024",
    fileType: "TXT",
    fileSize: "12 KB",
    mimeType: "text/plain",
    pageCount: 1,
    chunkCount: 5,
    processingStatus: "FAILED",
    publicationStatus: "DRAFT",
    failReason: "Không thể trích xuất văn bản. File có chứa các ký tự mã hóa không hợp lệ.",
  },
  {
    id: 105,
    title: "Thực hành Cơ sở dữ liệu",
    description: "Hướng dẫn cài đặt và truy vấn SQL trên hệ quản trị SQL Server.",
    subject: "Hệ thống thông tin",
    topic: "Cơ sở dữ liệu",
    tags: ["SQL", "Database", "Practice"],
    authorId: 3,
    authorName: "ThS. Trần Thị B",
    uploadedAt: "05/03/2024",
    updatedAt: "06/03/2024",
    fileType: "PDF",
    fileSize: "1.8 MB",
    mimeType: "application/pdf",
    pageCount: 60,
    chunkCount: 120,
    processingStatus: "PROCESSED",
    publicationStatus: "PUBLISHED",
    publishedAt: "06/03/2024",
    reviewedByName: "Phòng Đào Tạo",
  }
];
