-- Seed demo published documents for testing BE-07 Library API.
-- Run this after migrations and seed users are applied.

-- 1. Ensure a demo teacher exists (reuse hash from V3 seed, password: 123456)
INSERT INTO users (email, password, name, role, status)
VALUES ('demo.teacher@example.com',
        '$2b$10$VWWkkl.VSL6GL.sX7VGYGeTRbw2vMT80WJArUPDpSRRIapxROc8DW',
        'Demo Teacher',
        'TEACHER',
        'ACTIVE')
ON CONFLICT (email) DO NOTHING;

-- 2. Seed 5 PUBLISHED documents with varied metadata for filter testing
INSERT INTO documents (
    uploaded_by,
    title,
    description,
    subject,
    topic,
    chapter,
    tags,
    original_filename,
    stored_filename,
    storage_key,
    file_version,
    file_type,
    mime_type,
    file_size,
    processing_status,
    publication_status,
    rag_eligible,
    page_count,
    estimated_token_count,
    estimated_chunk_count,
    processed_at,
    reviewed_by,
    reviewed_at,
    published_at,
    created_at,
    updated_at
)
SELECT
    t.id,
    'Bài giảng Cơ sở dữ liệu',
    'Tài liệu nhập môn về cơ sở dữ liệu quan hệ và chuẩn hóa.',
    'Cơ sở dữ liệu',
    'Chuẩn hóa dữ liệu',
    'Chương 3',
    '["database", "normalization"]'::jsonb,
    'csdl.pdf',
    'source.pdf',
    'documents/demo-csdl/v1/source.pdf',
    1,
    'PDF',
    'application/pdf',
    1200000,
    'PROCESSED',
    'PUBLISHED',
    true,
    20,
    4200,
    48,
    NOW(),
    a.id,
    NOW(),
    NOW(),
    NOW(),
    NOW()
FROM users t, users a
WHERE t.email = 'demo.teacher@example.com'
  AND a.role = 'ADMIN'
LIMIT 1;

INSERT INTO documents (
    uploaded_by,
    title,
    description,
    subject,
    topic,
    chapter,
    tags,
    original_filename,
    stored_filename,
    storage_key,
    file_version,
    file_type,
    mime_type,
    file_size,
    processing_status,
    publication_status,
    rag_eligible,
    page_count,
    estimated_token_count,
    estimated_chunk_count,
    processed_at,
    reviewed_by,
    reviewed_at,
    published_at,
    created_at,
    updated_at
)
SELECT
    t.id,
    'Bài giảng Lập trình hướng đối tượng',
    'Giới thiệu các khái niệm class, object, inheritance và polymorphism.',
    'Lập trình hướng đối tượng',
    'Ngôn ngữ Java',
    'Chương 1',
    '["java", "oop"]'::jsonb,
    'oop.pdf',
    'source.pdf',
    'documents/demo-oop/v1/source.pdf',
    1,
    'PDF',
    'application/pdf',
    1500000,
    'PROCESSED',
    'PUBLISHED',
    true,
    35,
    6800,
    72,
    NOW(),
    a.id,
    NOW(),
    NOW(),
    NOW(),
    NOW()
FROM users t, users a
WHERE t.email = 'demo.teacher@example.com'
  AND a.role = 'ADMIN'
LIMIT 1;

INSERT INTO documents (
    uploaded_by,
    title,
    description,
    subject,
    topic,
    chapter,
    tags,
    original_filename,
    stored_filename,
    storage_key,
    file_version,
    file_type,
    mime_type,
    file_size,
    processing_status,
    publication_status,
    rag_eligible,
    page_count,
    estimated_token_count,
    estimated_chunk_count,
    processed_at,
    reviewed_by,
    reviewed_at,
    published_at,
    created_at,
    updated_at
)
SELECT
    t.id,
    'Bài giảng Mạng máy tính',
    'Giao thức TCP/IP, mô hình OSI và ứng dụng mạng.',
    'Mạng máy tính',
    'Giao thức TCP/IP',
    'Chương 2',
    '["network", "tcp"]'::jsonb,
    'network.pdf',
    'source.pdf',
    'documents/demo-network/v1/source.pdf',
    1,
    'PDF',
    'application/pdf',
    980000,
    'PROCESSED',
    'PUBLISHED',
    true,
    18,
    3100,
    36,
    NOW(),
    a.id,
    NOW(),
    NOW(),
    NOW(),
    NOW()
FROM users t, users a
WHERE t.email = 'demo.teacher@example.com'
  AND a.role = 'ADMIN'
LIMIT 1;

INSERT INTO documents (
    uploaded_by,
    title,
    description,
    subject,
    topic,
    chapter,
    tags,
    original_filename,
    stored_filename,
    storage_key,
    file_version,
    file_type,
    mime_type,
    file_size,
    processing_status,
    publication_status,
    rag_eligible,
    page_count,
    estimated_token_count,
    estimated_chunk_count,
    processed_at,
    reviewed_by,
    reviewed_at,
    published_at,
    created_at,
    updated_at
)
SELECT
    t.id,
    'Bài giảng Trí tuệ nhân tạo',
    'Các thuật toán machine learning cơ bản và ứng dụng.',
    'Trí tuệ nhân tạo',
    'Machine Learning',
    'Chương 4',
    '["ai", "ml"]'::jsonb,
    'ai.pdf',
    'source.pdf',
    'documents/demo-ai/v1/source.pdf',
    1,
    'PDF',
    'application/pdf',
    2100000,
    'PROCESSED',
    'PUBLISHED',
    true,
    42,
    8900,
    95,
    NOW(),
    a.id,
    NOW(),
    NOW(),
    NOW(),
    NOW()
FROM users t, users a
WHERE t.email = 'demo.teacher@example.com'
  AND a.role = 'ADMIN'
LIMIT 1;

INSERT INTO documents (
    uploaded_by,
    title,
    description,
    subject,
    topic,
    chapter,
    tags,
    original_filename,
    stored_filename,
    storage_key,
    file_version,
    file_type,
    mime_type,
    file_size,
    processing_status,
    publication_status,
    rag_eligible,
    page_count,
    estimated_token_count,
    estimated_chunk_count,
    processed_at,
    reviewed_by,
    reviewed_at,
    published_at,
    created_at,
    updated_at
)
SELECT
    t.id,
    'Bài giảng Phát triển Web',
    'Xây dựng REST API với Spring Boot và bảo mật cơ bản.',
    'Phát triển Web',
    'REST API',
    'Chương 5',
    '["web", "api"]'::jsonb,
    'web.pdf',
    'source.pdf',
    'documents/demo-web/v1/source.pdf',
    1,
    'PDF',
    'application/pdf',
    1350000,
    'PROCESSED',
    'PUBLISHED',
    true,
    28,
    5500,
    61,
    NOW(),
    a.id,
    NOW(),
    NOW(),
    NOW(),
    NOW()
FROM users t, users a
WHERE t.email = 'demo.teacher@example.com'
  AND a.role = 'ADMIN'
LIMIT 1;
